### 레이블인코더# [`sklearn.preprocessing`](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.preprocessing "sklearn.preprocessing").LabelEncoder[¶](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html#sklearn-preprocessing-labelencoder "Permalink to this heading")
* _class_ sklearn.preprocessing.LabelEncoder[[source]](https://github.com/scikit-learn/scikit-learn/blob/ff1023fda/sklearn/preprocessing/_label.py#L36)[¶](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html#sklearn.preprocessing.LabelEncoder "Permalink to this definition")
* 
Methods

[`fit`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html#sklearn.preprocessing.LabelEncoder.fit "sklearn.preprocessing.LabelEncoder.fit")(y)

Fit label encoder.

[`fit_transform`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html#sklearn.preprocessing.LabelEncoder.fit_transform "sklearn.preprocessing.LabelEncoder.fit_transform")(y)


In [9]:
from sklearn.preprocessing import LabelEncoder

items = ['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

#LabelEncoder를 객체로 생성한 후, fit()과 transform()으로 label 인코딩 수행.
encoder = LabelEncoder()
labels = encoder.fit_transform(items)
print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [7]:
print('인코딩 클래스:', encoder.classes_)

인코딩 클래스 ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


In [8]:
print('디코딩 원본 값:', encoder.inverse_transform([4,5,2,0,1,1,3,3]))

디코딩 원본 값: ['전자렌지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


### 원핫인코더 sklearn.preprocessing.OneHotEncoder¶
* class sklearn.preprocessing.OneHotEncoder(*, categories='auto', drop=None, sparse='deprecated', sparse_output=True, dtype=<class 'numpy.float64'>, handle_unknown='error', min_frequency=None, max_categories=None)[source]¶

*handle_unknown{‘error’, ‘ignore’, ‘infrequent_if_exist’}, default=’error’
Specifies the way unknown categories are handled during transform.
*‘error’ : Raise an error if an unknown category is present during transform.

‘ignore’ : When an unknown category is encountered during transform, the resulting one-hot encoded columns for this feature will be all zeros. In the inverse transform, an unknown category will be denoted as None.

In [16]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
X = np.array([["a"] * 5 + ["b"] * 20 + ["c"] * 10 + ["d"] * 3], dtype=object).T
ohe = OneHotEncoder(max_categories=3, sparse_output=False).fit(X)
ohe.infrequent_categories_
ohe.transform([["a"], ["b"]])

array([[0., 0., 1.],
       [1., 0., 0.]])

In [17]:
ohe_1 = OneHotEncoder(max_categories=3).fit(X)
ohe_1.transform([["a"], ["b"]])

<2x3 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [18]:
ohe_1 = OneHotEncoder(sparse_output=False).fit(X)
ohe_1.transform([["a"], ["b"]])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [29]:
# 유비온교재
# 먼저 숫자값으로 변환을 위해 LabelEncoder로 변환.
items = ['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']
encoder = LabelEncoder()
labels = encoder.fit_transform(items)
# 2차원 데이터로 변환.
labels = labels.reshape(-1,1)

# 원-핫 인코딩을 적용.
oh_encoder = OneHotEncoder()
oh_encoder.fit_transform(labels)
oh_labels = oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [ ]:
# DataEncoding2(강사님코드)도 참고.