In [1]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

LE = LabelEncoder()
LE.fit(items)
labels = LE.transform(items)
print('인코딩 변환값', labels)

인코딩 변환값 [0 1 4 5 3 3 2 2]


In [2]:
LE.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자렌지', '컴퓨터'], dtype='<U4')

In [3]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

LE = LabelEncoder()

labels = LE.fit_transform(items)
print('인코딩 변환값', labels)

인코딩 변환값 [0 1 4 5 3 3 2 2]


In [4]:
LE.inverse_transform([0,0,1])

array(['TV', 'TV', '냉장고'], dtype='<U4')

In [6]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

X = np.array([["a"] * 5 + ["b"] * 20 + ["c"] * 10 + ["d"] * 3], dtype=object).T
ohe = OneHotEncoder(max_categories=3, sparse=False).fit(X)
ohe.infrequent_categories_

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/preprocessing/_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


[array(['a', 'd'], dtype=object)]

In [7]:
ohe.transform([["a"], ["b"]])

array([[0., 0., 1.],
       [1., 0., 0.]])

In [8]:
ohe_1 = OneHotEncoder(max_categories=3).fit(X)
ohe_1.transform([["a"], ["b"]])

<2x3 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [9]:
ohe_2 = OneHotEncoder(sparse=False ,handle_unknown='ignore' ).fit(X)
ohe_2.transform([["a"], ["b"] ,["f"]])

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/preprocessing/_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
items =np.array( ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']).reshape(-1,1)

# items = np.array(items)
# print(items.shape)
# items = np.array(items).reshape(-1,1)
# print(items.shape)
oh_encoder= OneHotEncoder(sparse=False)
result = oh_encoder.fit_transform(items)

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/preprocessing/_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [13]:
result

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [14]:
import pandas as pd 
pd.DataFrame(result , columns=['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '믹서'])

TV  냉장고  전자렌지  컴퓨터  선풍기   믹서
0  1.0  0.0   0.0  0.0  0.0  0.0
1  0.0  1.0   0.0  0.0  0.0  0.0
2  0.0  0.0   0.0  0.0  1.0  0.0
3  0.0  0.0   0.0  0.0  0.0  1.0
4  0.0  0.0   0.0  1.0  0.0  0.0
5  0.0  0.0   0.0  1.0  0.0  0.0
6  0.0  0.0   1.0  0.0  0.0  0.0
7  0.0  0.0   1.0  0.0  0.0  0.0