### 다항선형회귀 [`sklearn.preprocessing`](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.preprocessing "sklearn.preprocessing").PolynomialFeatures[¶](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.PolynomialFeatures.html#sklearn-preprocessing-polynomialfeatures "Permalink to this heading")
* class sklearn.preprocessing.PolynomialFeatures(degree=2, *, interaction_only=False, include_bias=True, order='C')[source]¶

In [1]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np 

# 다항식으로 변환한 단항식 생성, [[0,1],[2,3]]의 2*2행렬 생성
X = np.arange(4).reshape(2,2)
print('일차 단항식 계수 feature:\n', X)

일차 단항식 계수 feature:
 [[0 1]
 [2 3]]


In [2]:
# degree=2 인 2차 다항식으로 변환 위해 PolynomialFeatures를 이용
poly = PolynomialFeatures(degree=2)
poly.fit(X)
poly_ftr = poly.transform(X)
print('변환된 2차 다항식 계수 feature:\n', poly_ftr)

변환된 2차 다항식 계수 feature:
 [[1. 0. 1. 0. 0. 1.]
 [1. 2. 3. 4. 6. 9.]]


In [3]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

X = np.arange(6).reshape(2,3)
print("일차 다항식 계수 : ",X)

poly = PolynomialFeatures(degree=2)
poly_ftr = poly.fit_transform(X)

print("변경된 2차 다항식 계수 : ",poly_ftr)

poly_3 = PolynomialFeatures(degree=3)
poly_3_ftr = poly_3.fit_transform(X)
print("3차 다항식 계수 : ", poly_3_ftr)

일차 다항식 계수 :  [[0 1 2]
 [3 4 5]]
변경된 2차 다항식 계수 :  [[ 1.  0.  1.  2.  0.  0.  0.  1.  2.  4.]
 [ 1.  3.  4.  5.  9. 12. 15. 16. 20. 25.]]
3차 다항식 계수 :  [[  1.   0.   1.   2.   0.   0.   0.   1.   2.   4.   0.   0.   0.   0.
    0.   0.   1.   2.   4.   8.]
 [  1.   3.   4.   5.   9.  12.  15.  16.  20.  25.  27.  36.  45.  48.
   60.  75.  64.  80. 100. 125.]]


In [ ]:
#파이프라인 이용
def polynomial_func(x):
    y = 1 + 2*x + x**2 + x**3
    return y

model = Pipeline([('poly', PolynomialFeatures(degree=3)),
                  ('linear', LinearRegression())])

x = np.arange(4).reshape(2,2)
y = polynomial_func(x)

model = model.fit(x,y)
print('Polynomial 회귀계수\n')